### ISSUE TITLE
有和MessagePack对比过性能吗？

### ISSUE THREAD

**Issue by qcjxberin** [Dogwei/Swifter.Json#1]
有和MessagePack对比过性能吗？

**Comment by Dogwei** [comment]
有呀，MesaagePack 还是快很多的。

**Comment by qcjxberin** [comment]
意思也就是说MessagePack比Swifter.Json要快了。

**Comment by Dogwei** [comment]
主要是构建protobuf数据结构非常快，json格式想要超越基本不可能了。

**Comment by Dogwei** [comment]
数据格式优势，json理论上不可能超越。

**Comment by sgf** [comment]
> 意思也就是说MessagePack比Swifter.Json要快了。

二进制序列化的优势就是 直接copy内存，json 字符串 无论怎么搞都多了一个内存到字符串的转换。
