### ISSUE TITLE
把 IgnoreCase 的设置放到 JsonFormatter 枚举中。方便不同的JsonFormatter 特殊化设置？

### ISSUE THREAD

**Issue by sgf** [Dogwei/Swifter.Json#11]
如题
目前的设置方式不是很友好
而且貌似据wiki的意思是 不支持多次修改。

**Comment by Dogwei** [comment]
下一版本我会默认开启忽略大小写。

**Comment by Dogwei** [comment]
下一版本我会默认开启忽略大小写。

IgnoreCase 这个配置无法加到 JsonFormatterOptions，因为 Swifter.Json 的解析器只解析出一个名称和值，然后提交给数据写入器，由数据写入器去做字段匹配。这样不管这个数据写入器是一个对象，或是一个字典，对于 Swifter.Json 都是一样的操作。

字段名称的匹配是在 FastObjectRW 中完成的，所以这个配置只能在 FastObjectRW 中设置。Swifter.Json 不会管这个操作。

不过您这个需求可以用 XObjectRW 实现，比较复杂，我可以在 Swifter.Json 下一版本中加入一些 XObjectRW 的扩展方法。

**Comment by sgf** [comment]
好吧，谢谢，不过之前 我用 Json.net的时候貌似可以指定的。

**Comment by Dogwei** [comment]
抱歉了，因为 Json.Net 并没有模块化。举例：在马上就要推出的 Swifter.MessagePack 也是在 Swifter.Core 之上实现，它会和 Swifter.Json 共用一个 FastObjectRW。其实 FastObjectRW 它是可以独立使用的工具，它可以很方便且灵活的操作对象数据。

Json.Net 的对象操作器与 Json 工具绑定，它无法单独工作，并且假如 Json.Net 的作者需要实现一个 MessagePack.Net，他必须从头到尾重写。

其实，目前我已知的 Json 工具，都并没有模块化，耦合度极高，几乎无法分离，这样本来是有性能优势的，但还是没有 Swifter.Json 快。

**Comment by sgf** [comment]
那就期待你的 Swifter.MessagePack 😀
.net 社区 有作者 已经很给力拉
