### ISSUE TITLE
关于JsonFormatterOptions.IgnoreNull和dynamic内包含日期的序列化

### ISSUE THREAD

**Issue by lovefather** [Dogwei/Swifter.Json#12]
首先我定义了一个类，用来返回数据

```
class ApiResult
{
    [RWField(Name = "code", Order = 1)]
    public int Code { get; set; }

    [RWField(Name = "msg", Order = 2)]
    public string Message { get; set; }

    [RWField(Name = "timestamp", Order = 3)]
    public long Timestamp => (long)(DateTime.Now.ToUniversalTime() - new DateTime(1970, 1, 1)).TotalMilliseconds;

    public static ApiResult Succeed() => new ApiResult { Code = 200 };
    public static ApiResult Failed(int code, string errorMessage) 
        => new ApiResult { Code = code, Message= errorMessage };
}

class ApiResult<T> : ApiResult
{
    public T Data { get; set; }

    public static ApiResult<T> Succeed(T data) => new ApiResult<T> { Code = 200, Data = data };
}
```

定义了一个用来测试的类
```
class Student
{
    public int No { get; set; }

    public string Name { get; set; }

    public string Addr { get; set; }

    [RWFormat("yyyy-MM-dd HH:mm:ss")]
    public DateTime Birthday { get; set; }
}
```

测试程序
```
class Program
{
    static void Main(string[] args)
    {
        var result1 = ApiResult<Student>.Succeed(new Student() { No = 1, Name = "张三", Addr = null, Birthday = DateTime.Now });
        var json1 = JsonFormatter.SerializeObject(result1);
        var json2 = JsonFormatter.SerializeObject(result1, JsonFormatterOptions.IgnoreNull);

        var result2 = ApiResult.Failed(400, "网络连接错误");
        var json3 = JsonFormatter.SerializeObject(result2);
        var json4 = JsonFormatter.SerializeObject(result2, JsonFormatterOptions.IgnoreNull);

        var stu = new { No = 1, Name = "张三", Addr = default(string), Birthday = DateTime.Now };
        var json5 = JsonFormatter.SerializeObject(ApiResult<dynamic>.Succeed(stu));

        Console.WriteLine(json1);
        Console.WriteLine(json2);
        Console.WriteLine(json3);
        Console.WriteLine(json4);
        Console.WriteLine(json5);

        Console.ReadKey();
    }
}
```
输出结果如下：
```
// json1
{"code":200,"msg":null,"timestamp":1563418324151,"Data":{"Addr":null,"Birthday":"2019-07-18 10:52:03","Name":"张三","No":1}}

// json2
{"code":200,"timestamp":1563418324195,"Data":{"Birthday":"2019-07-18 10:52:03","Name":"张三","No":1}}

// json3
{"code":400,"msg":"网络连接错误","timestamp":1563418324205}

// json4
{"code":400,"msg":"网络连接错误","timestamp":1563418324206}

// json5
{"code":200,"msg":null,"timestamp":1563418324213,"Data":{"Addr":null,"Birthday":"2019-07-18T10:52:04.206+08:00","Name":"张三","No":1}}
```

对比json1，json2这两个，其实更期望序列化后得到的结果为如下字符串：
`{"code":200,"timestamp":1563418324151,"Data":{"Addr":null,"Birthday":"2019-07-18 10:52:03","Name":"张三","No":1}}`

目前 `JsonFormatterSerializeObject<T>(T value, JsonFormatterOptions options)`方法在设置 options 为 `JsonFormatterOptions.IgnoreNull`时，会导致对象内所有为null的属性被忽略，无法得到上面期望的结果。

是否可以在`RWFieldAttribute`中增加对于是否忽略属性的功能支持（当类中某个属性标记为不忽略时，即便`options=JsonFormatterOptions.IgnoreNull`也不忽略此属性）

另外，对于json5，动态类型中的DateTime，序列化时如何设置指定格式呢？

**Comment by Dogwei** [comment]
感谢支持！

问题一可以用 RWObject 特性 解决：

        [RWObject(SkipDefaultValue = RWBoolean.Yes)]
        class ApiResult
        {
            [RWField(Name = "code", Order = 1)]
            public int Code { get; set; }

            [RWField(Name = "msg", Order = 2)]
            public string Message { get; set; }

            [RWField(Name = "timestamp", Order = 3)]
            public long Timestamp => (long)(DateTime.Now.ToUniversalTime() - new DateTime(1970, 1, 1)).TotalMilliseconds;

            public static ApiResult Succeed() => new ApiResult { Code = 200 };
            public static ApiResult Failed(int code, string errorMessage)
                => new ApiResult { Code = code, Message = errorMessage };
        }

使用 [RWObject(SkipDefaultValue = RWBoolean.Yes)] 和 JsonFormatterOptions.IgnoreNull 有一些区别：

SkipDefaultValue 会跳过任何类型的默认值：比如：0，null，DateTime.MinValue, Guid.Empty 等。
SkipDefaultValue 性能更快！并且是全局生效（即任何 JsonFormatter 的实例方法和静态方法都生效）。

更多方法看 ：https://github.com/Dogwei/Swifter.Json/wiki/序列化时忽略-Null-值

问题二有几种方式：
1:
var jsonFormatter = new JsonFormatter();

jsonFormatter.SetDataTimeFormat("yyyy-MM-dd");

Console.WriteLine(jsonFormatter.Serialize(new {DateTime = DateTime.Now}));
2:
首先定义一个 DateTimeInterface 
        public sealed class DateTimeInterface : IValueInterface<DateTime>
        {
            private readonly string format;

            public DateTimeInterface(string format)
            {
                this.format = format;
            }

            public DateTime ReadValue(IValueReader valueReader)
            {
                return valueReader.ReadDateTime();
            }

            public void WriteValue(IValueWriter valueWriter, DateTime value)
            {
                valueWriter.WriteString(value.ToString(format));
            }
        }

ValueInterface<DateTime>.SetInterface(new DateTimeInterface(“yyyy-MM-dd”));


Console.WriteLine(JsonFormatter.SerializeObject(new {DateTime = DateTime.Now}));


方式二是全局的，对所有实例和静态方法都生效。方式二相比方式一少了一个归属判断，所以性能快一点。

在之后的版本里，方式二可以在像方式一一样简单配置。只是抱歉，目前发布的版本中没有。
