### ISSUE TITLE
Swifter 反序列话,Json串比实体字段多,出现异常

### ISSUE THREAD

**Issue by lzghuluwa** [Dogwei/Swifter.Json#13]
目前我的情况出现,我存储的Json 串 比对应实体字段多,会出现这种情况,怎么解决呢？这种情况就不能在实体里面设置对应的属性了。 比如我有个json 串 {"Test":"1",Id:1},但是我的实体只有Id 字段。

![image](https://user-images.githubusercontent.com/17671077/61681040-65dbec00-ad3e-11e9-842e-42fafcab22af.png)

**Comment by Dogwei** [comment]
感谢支持！

您可以查看 Wiki：https://github.com/Dogwei/Swifter.Json/wiki/设置属性不存在或无-get-set-方法时的异常行为 这里有解决方案。

**Comment by lzghuluwa** [comment]
> 感谢支持！
> 
> 您可以查看 Wiki：[https://github.com/Dogwei/Swifter.Json/wiki/设置类型属性的异常行为](https://github.com/Dogwei/Swifter.Json/wiki/%E8%AE%BE%E7%BD%AE%E7%B1%BB%E5%9E%8B%E5%B1%9E%E6%80%A7%E7%9A%84%E5%BC%82%E5%B8%B8%E8%A1%8C%E4%B8%BA) 这里有解决方案。

您好,我的意思是我现在已经有一批json数据,目前只是对应的实体里面没有。这些数据更新起来也比较困难,您的案例里面是在属性上设置忽略,再反序列话，但是我的情况刚好相反,我是现有json 然后有的实体。而且实体既有可能比json 里面的字段少。

**Comment by lzghuluwa** [comment]
> 感谢支持！
> 
> 您可以查看 Wiki：[https://github.com/Dogwei/Swifter.Json/wiki/设置类型属性的异常行为](https://github.com/Dogwei/Swifter.Json/wiki/%E8%AE%BE%E7%BD%AE%E7%B1%BB%E5%9E%8B%E5%B1%9E%E6%80%A7%E7%9A%84%E5%BC%82%E5%B8%B8%E8%A1%8C%E4%B8%BA) 这里有解决方案。

非常感谢您的支持,问题已解决
