### ISSUE TITLE
Support Type Declaration in JSON?

### ISSUE THREAD

**Issue by ghost** [Dogwei/Swifter.Json#14]
In Newtonsoft.Json, we can define the data type of the $data field through the $type pseudo-field to avoid data type ambiguity in RPC. Does Swifter.Json support the above features?

在Newtonsoft.Json中，我们可以通过 $type 伪字段来定义 $data 字段的数据类型，避免RPC时数据类型歧义。请问Swifter.Json支持上述功能吗？

**Comment by Dogwei** [comment]
目前还没有。这个功能很棒，我在下一版本中加入。我将在这里发布实现原理可以吗？

**Comment by ghost** [comment]
> 目前还没有。这个功能很棒，我在下一版本中加入。我将在这里发布实现原理可以吗？

Thanks and looking forward! Would love to migrate to Swifter.Json when this new feature is established.
