### ISSUE TITLE
关于在 Controller 上使用 [Produces("application/json")] 特性的问题

### ISSUE THREAD

**Issue by Lucifer2031** [Dogwei/Swifter.Json#15]
+ 测试环境：Asp.Net Core 3.0 Preview 8
+ 插件版本：Swifter.Extensions.AspNetCore v1.2.9.2

今天意外发现了一个问题，我不知道这种行为是否正常，还是 BUG。比如，下面的问题代码：

```csharp
    [Produces("application/json")]
    [ApiController]
    [Route("api/[controller]")]
    public class TestController : ControllerBase
    {
        [HttpGet]
        public ActionResult<string> Get([FromQuery, BindRequired] string name)
        {
            return Ok(name);
        }
    }
```

这时候，访问 http://localhost:5000/api/Test?name=Test 就会报以下错误：

> An unhandled exception occurred while processing the request.
> ArgumentNullException: Value cannot be null. (Parameter 'encoding')
> Microsoft.AspNetCore.Mvc.Infrastructure.MemoryPoolHttpResponseStreamWriterFactory.CreateWriter(Stream stream, Encoding encoding)

但是，这种行为在 Asp.Net Core 3.0 Preview 8 默认生成的模板程序中会正常返回一个字符串。

临时解决办法是 return new JsonResult(name);

**Comment by Dogwei** [comment]
您好，我今天发布了 Swifter.Extensions.AspNetCore v1.2.9.5，您更新一下就可以解决了。

**Comment by Lucifer2031** [comment]
好的，感谢您做出的卓越工作。
