### ISSUE TITLE
Swifter.Json 序列化 enum 和 DateTime 不正确的问题

### ISSUE THREAD

**Issue by Lucifer2031** [Dogwei/Swifter.Json#18]
+ 测试环境：.NET Core 3.0 Preview 9
+ Package 版本：Swfiter.Json v1.2.9.5 & Swifter.Extensions.AspNetCore v1.2.9.5

问题如下：

+ 序列化 enum 时，序列化的结果是枚举的属性名称，而不是属性的值；
+ 序列化 DateTime 时，序列化的结果是 DateTimeOffset 的值，而不是 DateTime 的值，带有时区信息；

**Comment by Dogwei** [comment]
关于枚举的话，暂时没有配置项，我将在下一版本加入可配置项。

关于 DateTime 的处理的话，Swifter.Json 使用 ISO8601 标准格式，默认时区为本地时区。如果您像修改日期格式，您可以这样写 Swifter.RW.ValueInterface.SetValueFormat<DateTime>("yyyy-MM-dd HH:mm:ss");

**Comment by Lucifer2031** [comment]
DateTime 这样处理是不正确的。DateTime 本身只有 Local，Unspecified，UTC 三种格式，本身不带有时区信息，默认带有时区信息是不对的。何况还是本地时区。UTC 怎么办？

如果用户采用时区方案，肯定会使用 DateTimeOffset，而且这个时区不一定是本地时区。

ISO8601 标准格式里，也包含不带有时区的时间格式。
