### ISSUE TITLE
JsonFormatterOptions.MultiReferencingNull breaks multi-dimensional arrays

### ISSUE THREAD

**Issue by alexmg** [Dogwei/Swifter.Json#19]
When the `JsonFormatterOptions.MultiReferencingNull` option is enabled the output of each dimension in a multi-dimensional array is always `null`.

The LINQPad statements below demonstrate the problem.

```
var foo = new[,] { { 1, 2, 3 }, { 4, 5, 6 } };

JsonFormatter.SerializeObject(foo)
    .Dump("Without MultiReferencingNull");

JsonFormatter.SerializeObject(foo, JsonFormatterOptions.MultiReferencingNull)
    .Dump("With MultiReferencingNull");
```

Without `MultiReferencingNull`: `[[1,2,3],[4,5,6]]`

With `MultiReferencingNull`: `[null,null]`

I discovered this issue when upgrading from `1.1.2` to `1.2.9.5`.

**Comment by Dogwei** [comment]
I'm so sorry, I didn't sign in to GITHUB lately because I'm busy working for the company.

I noticed this problem, it is the BUG that is produced by refactoring.

I'll to release a small version today or tomorrow to fix known problems.

Thank you for your support.

**Comment by alexmg** [comment]
No problem. I completely understand. Looking forward to the fix.

**Comment by alexmg** [comment]
This appears to be still be an issue in `1.2.9.6`. Is the release that contains the fix still pending?
