### ISSUE TITLE
CamelCase support?

### ISSUE THREAD

**Issue by Jusfrw** [Dogwei/Swifter.Json#2]
As title, thx.

**Comment by Dogwei** [comment]
yes. it also support ignore case.

**Comment by Svetomechc** [comment]
@Dogwei
How do I enable it? I want my controllers to return JSON in camelCase, but with your library all JSON is returned in PascalCase.

**Comment by Svetomechc** [comment]
@Dogwei I looked into **Swifter.Json.JsonFormatterOptions** and **Swifter.Json.JsonFormatter**, but I don't see anything there that would enable PascalCase in output formatting.

**Comment by Svetomechc** [comment]
Please reopen.
