### ISSUE TITLE
序列化double,float这些小数格式化有问题,位数和数值不对

### ISSUE THREAD

**Issue by yekainew** [Dogwei/Swifter.Json#20]
DateTime? time2 = null;
            Hashtable hs = new Hashtable();
            hs["name"] = "xiaocui";
            hs["time"] = DateTime.Now;
            hs["time2"] = time2;
            hs["count"] = int.MaxValue;
            hs["money"] = decimal.MinValue;
            hs["double_test"] = 3.1415;
            hs["float_test"] = 3.1415;
            var json = JsonFormatter.SerializeObject(hs);

            Response.Clear();
            Response.Write(json);

.net4.5输出结果
{"money":-79228162514264337593543950335,"count":2147483647,"float_test":3.1415000000000002,"time2":null,"time":"2019-09-21T22:35:03.870+08:00","name":"xiaocui","double_test":3.1415000000000002}

我的值3.1415 变成了3.1415000000000002

**Comment by Dogwei** [comment]
非常抱歉了，最近忙于公司的工作没有上 GITHUB。
这个问题我已经注意到了，是因为新版本重构时产生了 BUG。
我今天将更新一个小版本修复已知问题。
感谢支持~
