### ISSUE TITLE
设置jsonFormatter实例的ValueInterface不生效

### ISSUE THREAD

**Issue by aprilyush** [Dogwei/Swifter.Json#22]
在基于net4.6.1的项目使用时
使用ValueInterface<DateTime>.SetInterface(new DateInterface());全局设置有效，单独设置不生效
`  
static void SwiferJsonTest()
        {
            var model = new TestDemo();
            model.Id = 1;
            model.LongId = 123213213212;
            model.InsertTime = DateTime.Now;

            // 只要类型是 LongId 的值都会走 LongIdInterface。
            // ValueInterface<long>.SetInterface(new LongIdInterface());
            // ValueInterface<DateTime>.SetInterface(new DateInterface());

            var json = JsonFormatter.SerializeObject(model);
            Console.WriteLine(json);

            Console.WriteLine("************************");
            var jsonFormatter = new JsonFormatter();
            // 此方式只会对 jsonFormatter 这个实例生效。
            jsonFormatter.SetValueInterface(new DateInterface());
            var json2 = jsonFormatter.Serialize(model);
           
            Console.WriteLine(json2);

        }
        public class TestDemo
        {
            public int Id { get; set; }
            public long LongId { get; set; }
            public DateTime InsertTime { get; set; }
        }

        public class DateInterface : IValueInterface<DateTime>
        {
            public DateTime ReadValue(IValueReader valueReader)
            {
                return DateTime.Parse(valueReader.ReadString());
            }

            public void WriteValue(IValueWriter valueWriter, DateTime value)
            {
                valueWriter.WriteString(value.ToString("yyyy-MM-dd"));
            }
        }
`

序列化处理的Json的时间格式还是原始格式 不是yyyy-MM-dd ，设置全局的情况下 是序列化处理的格式是正常的

**Comment by Dogwei** [comment]
非常抱歉了，最近忙于公司的工作没有上 GITHUB。
我今天将更新一个小版本修复已知问题，并且针对 .NET FW 平台多做测试。
感谢支持~

**Comment by aprilyush** [comment]
您好 今天拉nuget最新版本1.2.9.6测试问题依旧，查看bin目录下文件版本发现文件的版本依旧1.2.9.5

**Comment by Dogwei** [comment]
导致这个问题的原因是 FastObjectRW&lt;TestDemo&gt; 在初始化之后内部会优化基础类型（DateTime, long 等）的处理方法，导致 SetValueInterface 不生效。

而 Serialize&lt;TestDemo&gt; 或 Deserialize&lt;TestDemo&gt; 方法（静态方法也是）会初始化 FastObjectRW&lt;TestDemo&gt; 类。

解决办法有两个：
1：SetValueInterface&lt;TestDemo> 要在任何 Serialize&lt;TestDemo&gt; 或 Deserialize&lt;TestDemo&gt; 方法之前！
2：取消 FastObjectRW 对基础类型的优化：FastObjectRW.DefaultOptions &= ~FastObjectRWOptions.BasicTypeDirectCallMethod;（此配置要在程序初始化时配置，后期配置无效）

**Comment by Dogwei** [comment]
我稍后在 Wiki 上强调这一项的说明，感谢支持。

**Comment by Dogwei** [comment]
1.2.9.6 版本只升级的 Swifter.Core 和 Swifter.Unsafe 程序，Swifter.Json 并没有升级哦。

**Comment by aprilyush** [comment]
1：SetValueInterface<TestDemo> 要在任何 Serialize<TestDemo> 或 Deserialize<TestDemo> 方法之前！  
这个解决方案感觉不太合适 这样就是全局的设置了 我看你写的文档明确说明了 
` var jsonFormatter = new JsonFormatter();
        // 此方式只会对 jsonFormatter 这个实例生效。
        jsonFormatter.SetValueInterface(new DateInterface());`
按道理 我每次实例化JsonFormatter 都是独立的 应该不受其他影响
