### ISSUE TITLE
Deserialize Type DateTime? Exception

### ISSUE THREAD

**Issue by Mcgrady2009** [Dogwei/Swifter.Json#28]
var result = Swifter.Json.JsonFormatter.DeserializeObject<**DateTime?**>("");
Throw Exception
Value cannot be null.
Parameter name: chars

Why not return **null**
Another issue
Class contains field
```
[Swifter.RW.RWFormat("yyyy-MM-dd")]
public DateTime? time { get; set; }
```
SerializeObject Throw Exception
Field type 'System.Nullable`1[System.DateTime]' does not implement 'System.IFormattable' interface.

**Comment by Dogwei** [comment]
I'm sorry, i probably won't do it, because I think that's reasonable.
