### ISSUE TITLE
设置CannotSetException不生效

### ISSUE THREAD

**Issue by Tw1999** [Dogwei/Swifter.Json#35]
```
FastObjectRW.DefaultOptions &= ~FastObjectRWOptions.CannotSetException;

var obj1 = new ApiResult();
var obj2 = JsonFormatter.DeserializeObject(JsonFormatter.SerializeObject(obj1), typeof(ApiResult));
```

```
public class ApiResult
{
    [RWField(Name = "timestamp", Order = 99)]
    [RWObject(CannotSetException = RWBoolean.No)]
    public long Timestamp => (long)(DateTime.Now.ToUniversalTime() - new DateTime(1970, 1, 1)).TotalMilliseconds;
}
```

尝试了试用`FastObjectRW.DefaultOptions &= ~FastObjectRWOptions.CannotSetException;`或者`[RWObject(CannotSetException = RWBoolean.No)]`都不行，均会引发异常

**Comment by Dogwei** [comment]
[RWObject(CannotSetException = RWBoolean.No)]
public class ApiResult
{
    [RWField(Name = "timestamp", Order = 99)]
    public long Timestamp => (long)(DateTime.Now.ToUniversalTime() - new DateTime(1970, 1, 1)).TotalMilliseconds;
}

**Comment by Dogwei** [comment]
RWObject 特性应该放置在类上面
