### ISSUE TITLE
请问是否线程安全？

### ISSUE THREAD

**Issue by linng** [Dogwei/Swifter.Json#36]
在多线程下会抛出Failed to create FastObjectRW of 'XXXXX' type异常。

**Comment by Dogwei** [comment]
能否说明一下您的类和平台环境？

**Comment by linng** [comment]
> 能否说明一下您的类和平台环境？

Unity2019.2.15f1，Mono 4.x，在多线程做多个类（20个对象类）的大数据量（大于1000条）的反序列化时会抛出，加锁后正常。调用的接口为public static object DeserializeObject(string text, Type type, JsonFormatterOptions options);

对象类结构简单，只有属性。例如：
    public class UserData {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int IsDeleted { get; set; }
    }
