### ISSUE TITLE
生态

### ISSUE THREAD

**Issue by caobingsheng** [Dogwei/Swifter.Json#4]
大哥，你这性能确实高，但是SpanJson有AspNetCore插件，你赶紧跟上啊，一个小小的库也得有生态啊
有生态才有流行度，先让它火起来

**Comment by Dogwei** [comment]
好哦，我这段时间会写出很多示范类，示范如何利用 Swifter 各种强大功能来扩展出自己想要的功能，因为我个人始终无法想到所有人想要的功能。

这些示范类包括：特性定义类型的行为格式；在 Asp.Net 和 MVC 中使用 JsonFormmatter；让对象忽略大小写，跳过默认值，定义异常处理方式等。

Swifter 的扩展性很好，它甚至可以很轻松的写出一个新的格式支持，如果时间允许我可能还会写一个 MessagePack 的扩展。
