### ISSUE TITLE
反序列化 IEnumerable<T> 类型的属性，反序列化的值会错乱

### ISSUE THREAD

**Issue by asyura** [Dogwei/Swifter.Json#41]
如果对象有几个  IEnumerable&lt;T&gt; 类型的属性，T是同一种类型，但属性的值不一样。这种情况反序列化后，这几个属性的值会错乱。。
项目中已经用了Swiftre.Json，能不能查看下，尽快修复发布一个版本呢，谢谢啦

**Comment by asyura** [comment]
比如下面的JSON，反序列化后INPUTS的值里面包含了OUTPUTS的内容，INPUTS和OUTPUTS都是IEnumerable类型
`
{    
    "F_T_ID": "E2PiZTZT-EahMW38p3VE-g",
    "F_TITLE": "数学计算策略",
    "INPUTS": [
        {
            "F_NAME": "X",
            "F_PARA_ID": "D9Z6gicly0uyfivMiF_hjQ"
        },
        {
            "F_NAME": "Y",
            "F_PARA_ID": "HS47mCTZM0Set8WHGOJQ5Q"
        },
        {
            "F_NAME": "OP",
            "F_PARA_ID": "tIcsfnCvAE-o7b6FjhXtGw"
        }
    ],    
    "OUTPUTS": [
        {
            "F_NAME": "Z",
            "F_PARA_ID": "TvG7Q7vlyEOrxMDZAWnY6w"
        }
    ],
    "PARAS": null
}
`

**Comment by Dogwei** [comment]
抱歉这么久才回复，新版本已经发布，这个问题已解决。您可以加入我们的 QQ 群：133630914，可以更快的给您反馈。
