### ISSUE TITLE
枚举序列化

### ISSUE THREAD

**Issue by zxyao145** [Dogwei/Swifter.Json#6]
请问如何在序列化/反序列化的时候使用枚举值而不是flag？flag只是一堆数字，不利用阅读

**Comment by Dogwei** [comment]
FastObjectRW<object>.CurrentOptions ^=
                 FastObjectRWOptions.BasicTypeDirectCallMethod;
您在程序初始化的处增加这一句。（using Swifter.RW;）

**Comment by zxyao145** [comment]
> ```
>         FastObjectRW<object>.CurrentOptions ^=
>              FastObjectRWOptions.BasicTypeDirectCallMethod;
> ```
> 您在程序初始化的处增加这一句。（using Swifter.RW;）

有用，谢谢！

**Comment by Dogwei** [comment]
感谢支持！
