### ISSUE TITLE
序列化自定义类 数组报空指针

### ISSUE THREAD

**Issue by xiwenlong** [Dogwei/Swifter.Json#66]
序列化自定义类型的数组，数组中有null，第一次可以序列化，第二次在执行一遍就会有空指针错误。
使用数组跳过空值设定可以解决这个问题，但是我想要存null进去占位。
![image](https://github.com/Dogwei/Swifter.Json/assets/44190160/69b09849-2715-4e87-b134-5c7a1461edfd)

![image](https://github.com/Dogwei/Swifter.Json/assets/44190160/ad6ec5e8-f49e-4d36-a4bb-a2a7ef264b33)

**Comment by Dogwei** [comment]
问题已经修复，导致这个问题的原因是新版本对实体集合类型进行了性能优化（第二次操作该实体类型的集合时生效），但我此处忽略了对 null 的判断。

如图，之前不含框选的代码。
![image](https://github.com/Dogwei/Swifter.Json/assets/14845492/ba0226d8-1787-4444-a620-940b76b29917)
