### ISSUE TITLE
序列化所有Enum 能否简单的做到序列化成数字？即int 另外枚举数字是可以是负数的啊？

### ISSUE THREAD

**Issue by worldofchu** [Dogwei/Swifter.Json#68]
序列化所有Enum 能否简单的做到序列化成数字？即int 另外枚举数字是可以是负数的啊？

**Comment by Dogwei** [comment]
我在 Github 上新增了 Wiki 页面。演示如何在 Swifter.Json 中 [将枚举默认序列化为数字格式](https://github.com/Dogwei/Swifter.Json/wiki/将枚举默认序列化为数字格式)。
