### ISSUE TITLE
反序列化含无set方法的属性的类时出现异常

### ISSUE THREAD

**Issue by AlaricGilbert** [Dogwei/Swifter.Json#7]
dotnet sdk版本：2.2.105
反序列化含无set方法的属性时出错
例如：
命名空间System.Net下的`Cookie`类的某个实例经Swifter.JSON序列化后形成如下的json
```json
{
            "Comment": "",
            "CommentUri": null,
            "Discard": false,
            "Domain": ".bilibili.com",
            "Expired": false,
            "Expires": "2019-05-19T09:51:39.000+08:00",
            "HttpOnly": false,
            "Name": "bili_jct",
            "Path": "/",
            "Port": "",
            "Secure": false,
            "TimeStamp": "2019-04-19T09:51:41.313+08:00",
            "Value": "some_value",
            "Version": 0
}
```
浏览sdk定义可发现其中`TimeStamp`属性无set访问器。
![image](https://user-images.githubusercontent.com/36405110/56401220-69b52980-628a-11e9-939b-7d5ec2d59c9d.png)

在反序列化这个json为Cookie类的实例时出现异常。
![image](https://user-images.githubusercontent.com/36405110/56401207-573af000-628a-11e9-80e0-b85373d940d1.png)

**Comment by Dogwei** [comment]
当前发布版本就有这个配置，您在程序初始化时加上 --

FastObjectRW&lt;object&gt;.CurrentOptions &= ~FastObjectRWOptions.CannotSetException;

FastObjectRWOptions.CannotSetException 这个配置是指当属性没有 set 方法时调用 WriteValue 会抛出一个异常。取消掉这个配置那么就是不 set 也不抛出异常。
