### ISSUE TITLE
弱弱的问一下，这块支持dynamic吗

### ISSUE THREAD

**Issue by yh371174229** [Dogwei/Swifter.Json#8]
弱弱的问一下，这块支持dynamic吗

**Comment by Dogwei** [comment]
抱歉这么晚才回复。

因为早期想法很单纯：“DynamicObject 内部就是 Dictionary<string, object>，所以我直接解析 Dictionary<string, object> 效果是一样的”。

所以目前是没有提供 DynamicObject 的存储结构的。

不过既然有需要，那我就会新增这个对象的。

**Comment by Dogwei** [comment]
您好，在昨天发布的 1.2.0 版本中可以这样获取 dynamic 对象。

dynamic dynamicObject = JsonFormatter.DeserializeObject<JsonValue>(json);

var val = dynamicObject.Id; // only json object operation.
var ele = dynamicObject[0]; // only json array operation.

**Comment by yh371174229** [comment]
好的 一会儿我去使用一下 感谢大佬
