### ISSUE TITLE
关于字典和枚举

### ISSUE THREAD

**Issue by CarlaX** [Dogwei/Swifter.Json#9]
如果字典的Key是枚举类型，序列化的时候会被忽略；如果字典的Value是枚举类型，可以序列化，但是，枚举没有以索引保存而是转成了字符串，这样无法被反序列化。不知道是不是我用法有问题，请问有没有什么设置可以解决或者考虑在新版本添加下支持，多谢。

**Comment by Dogwei** [comment]
抱歉这么晚才回复，因为之前有朋友提过类似的问题，所以您一说我就明白是哪里出的问题了。

因为 Type.GetTypeCode 会把枚举识别为 TypeCode.Int32....

类似这样的错误已经全部解决，晚上我就上传新版本。

因为最近时间有限，所以这次只上版本，不写说明。
